-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['task'::text, 'project'::text, 'document'::text, 'event'::text, 'contact'::text])),
  entity_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['created'::text, 'updated'::text, 'deleted'::text, 'commented'::text, 'assigned'::text, 'completed'::text, 'archived'::text, 'restored'::text])),
  description text,
  changes jsonb,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  devis_id uuid,
  type text CHECK (type = ANY (ARRAY['Service'::text, 'Produit'::text, 'Abonnement'::text])),
  description text,
  quantity numeric,
  unit_price numeric,
  tax numeric,
  created_at timestamp with time zone DEFAULT now(),
  facture_id uuid,
  CONSTRAINT articles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['physical'::character varying, 'digital'::character varying]::text[])),
  description text,
  acquisition_date timestamp with time zone DEFAULT now(),
  expiration_date timestamp with time zone,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'pending'::character varying, 'archived'::character varying]::text[])),
  value numeric,
  currency character varying DEFAULT 'EUR'::character varying,
  location character varying,
  file_path character varying,
  metadata jsonb,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT assets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['task'::text, 'project'::text, 'document'::text, 'event'::text, 'comment'::text])),
  entity_id uuid NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  file_type text,
  mime_type text,
  uploaded_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT attachments_pkey PRIMARY KEY (id),
  CONSTRAINT attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['task'::text, 'project'::text, 'document'::text, 'event'::text])),
  entity_id uuid NOT NULL,
  content text NOT NULL,
  author_id uuid,
  parent_comment_id uuid,
  reactions jsonb DEFAULT '{}'::jsonb,
  is_edited boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  phone text,
  type text NOT NULL CHECK (type = ANY (ARRAY['board-member'::text, 'external'::text, 'freelance'::text, 'member'::text, 'network'::text, 'partner'::text, 'waitlist'::text, 'blacklist'::text, 'lead'::text, 'client'::text, 'investor'::text])),
  status text NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  company text,
  position text,
  tags ARRAY,
  service text,
  waitlist_position integer,
  joined_at timestamp with time zone,
  reason text,
  added_by uuid,
  expires_at timestamp with time zone,
  source text,
  probability integer CHECK (probability >= 0 AND probability <= 100),
  last_contacted_at timestamp with time zone,
  next_follow_up timestamp with time zone,
  estimated_value numeric,
  first_contact_date timestamp with time zone,
  last_purchase_date timestamp with time zone,
  total_spent numeric DEFAULT 0,
  investment_stage text CHECK (investment_stage = ANY (ARRAY['seed'::text, 'series-a'::text, 'series-b'::text, 'series-c'::text, 'growth'::text, 'private-equity'::text])),
  investment_focus ARRAY,
  portfolio_companies ARRAY,
  minimum_check_size numeric,
  maximum_check_size numeric,
  preferred_industries ARRAY,
  last_contact_date timestamp with time zone,
  investment_status text CHECK (investment_status = ANY (ARRAY['active'::text, 'inactive'::text, 'following'::text, 'not-interested'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  lead_source text,
  lead_score integer CHECK (lead_score >= 0 AND lead_score <= 100),
  client_since timestamp with time zone,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_added_by_fkey FOREIGN KEY (added_by) REFERENCES auth.users(id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  slug character varying,
  data_type character varying NOT NULL,
  content text,
  summary text,
  author_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  status character varying DEFAULT 'draft'::character varying,
  category character varying,
  tags ARRAY,
  featured_image_url text,
  media_urls ARRAY,
  metadata jsonb,
  is_public boolean DEFAULT true,
  visibility_level character varying DEFAULT 'public'::character varying,
  search_vector tsvector DEFAULT ((setweight(to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying))::text), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(content, ''::text)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(summary, ''::text)), 'C'::"char")),
  CONSTRAINT data_pkey PRIMARY KEY (id),
  CONSTRAINT data_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.document_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  category text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT document_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  document_type_id uuid NOT NULL,
  custom_type text,
  file_path text,
  file_name text,
  file_size integer,
  file_type text,
  version text,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Active'::text, 'Archived'::text, 'Deleted'::text])),
  project_id uuid,
  contact_id uuid,
  created_by uuid,
  last_modified_by uuid,
  is_template boolean DEFAULT false,
  metadata jsonb,
  tags ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT documents_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT documents_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id),
  CONSTRAINT fk_document_type FOREIGN KEY (document_type_id) REFERENCES public.document_types(id),
  CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_contact FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.events (
  event_id integer NOT NULL DEFAULT nextval('events_event_id_seq'::regclass),
  title character varying NOT NULL,
  description text,
  event_type character varying,
  location character varying,
  start_datetime timestamp without time zone NOT NULL,
  end_datetime timestamp without time zone,
  is_all_day boolean DEFAULT false,
  priority smallint DEFAULT 0,
  status character varying DEFAULT 'scheduled'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  attendees jsonb DEFAULT '[]'::jsonb,
  recurrence jsonb,
  CONSTRAINT events_pkey PRIMARY KEY (event_id)
);
CREATE TABLE public.formations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  category text,
  level text CHECK (level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text])),
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  duration_hours numeric NOT NULL,
  max_participants integer,
  format text CHECK (format = ANY (ARRAY['online'::text, 'in-person'::text, 'hybrid'::text])),
  language text DEFAULT 'fr'::text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  schedule text,
  objectives ARRAY,
  prerequisites ARRAY,
  program jsonb DEFAULT '[]'::jsonb,
  materials ARRAY,
  instructor_id uuid,
  instructor_name text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text, 'archived'::text])),
  current_participants integer DEFAULT 0,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT formations_pkey PRIMARY KEY (id),
  CONSTRAINT formations_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.contacts(id),
  CONSTRAINT formations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  type text CHECK (type = ANY (ARRAY['product'::text, 'service'::text, 'subscription'::text, 'bundle'::text, 'other'::text])),
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  original_price numeric,
  features ARRAY,
  limitations ARRAY,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  is_limited_time boolean DEFAULT false,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text, 'expired'::text, 'archived'::text])),
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  discount_percentage numeric DEFAULT 0 CHECK (discount_percentage >= 0::numeric AND discount_percentage <= 100::numeric),
  services jsonb DEFAULT '[]'::jsonb,
  duration_months integer,
  features ARRAY,
  benefits ARRAY,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text, 'archived'::text])),
  is_popular boolean DEFAULT false,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  type character varying NOT NULL,
  description text,
  price numeric,
  cost numeric,
  currency character varying DEFAULT 'EUR'::character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'discontinued'::character varying, 'draft'::character varying, 'archived'::character varying]::text[])),
  supplier_id uuid,
  supplier_name character varying,
  sku character varying,
  stock_quantity integer DEFAULT 0,
  metadata jsonb,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  project_type text NOT NULL CHECK (project_type = ANY (ARRAY['Client'::text, 'Internal'::text, 'Partner'::text, 'Lead'::text])),
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Completed'::text, 'On Hold'::text, 'Cancelled'::text])),
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  budget numeric,
  primary_contact_id uuid,
  team_contacts jsonb DEFAULT '[]'::jsonb,
  contact_roles jsonb DEFAULT '{}'::jsonb,
  tags ARRAY,
  priority text DEFAULT 'Medium'::text CHECK (priority = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Urgent'::text])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_primary_contact_id_fkey FOREIGN KEY (primary_contact_id) REFERENCES public.contacts(id),
  CONSTRAINT fk_primary_contact FOREIGN KEY (primary_contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text CHECK (category = ANY (ARRAY['consulting'::text, 'development'::text, 'design'::text, 'marketing'::text, 'training'::text, 'support'::text, 'other'::text])),
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  billing_type text DEFAULT 'one-time'::text CHECK (billing_type = ANY (ARRAY['one-time'::text, 'hourly'::text, 'daily'::text, 'monthly'::text, 'yearly'::text])),
  duration_hours numeric,
  deliverables ARRAY,
  requirements ARRAY,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text, 'archived'::text])),
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'todo'::text CHECK (status = ANY (ARRAY['todo'::text, 'in_progress'::text, 'in_review'::text, 'blocked'::text, 'done'::text, 'archived'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  created_by uuid,
  assignee_ids ARRAY,
  start_at timestamp with time zone,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  estimate_hours numeric,
  actual_hours numeric,
  parent_task_id uuid,
  order_index integer DEFAULT 0,
  comments jsonb NOT NULL DEFAULT '[]'::jsonb,
  info jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.contacts(id),
  CONSTRAINT tasks_parent_task_id_fkey FOREIGN KEY (parent_task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.time_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid,
  project_id uuid,
  user_id uuid,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  duration_minutes integer,
  description text,
  billable boolean DEFAULT true,
  hourly_rate numeric,
  status text DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'paused'::text, 'completed'::text, 'cancelled'::text])),
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT time_entries_pkey PRIMARY KEY (id),
  CONSTRAINT time_entries_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT time_entries_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT time_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  avatar_url text,
  phone text,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text, 'manager'::text, 'viewer'::text])),
  email_verified boolean DEFAULT false,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text, 'pending'::text])),
  last_login timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  contact_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);